id: A31D10FC8
title: A Plaintive Prayer to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:39:49.661427
  last_modified_at: 2022-03-01 00:39:49.661435
