id: A31D10FC8
title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:39:49.665959
  last_modified_at: 2022-03-01 00:39:49.665965
