id: A31D10FC8
title: Prayer to His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:39:49.668699
  last_modified_at: 2022-03-01 00:39:49.668708
